name: cifar10_demo_aws
workspace: HPE Instructors
project: cifar10
resources: 
  resource_pool: compute-pool
  slots_per_trial: 1
hyperparameters:
  learning_rate: 1.0e-4
  learning_rate_decay: 1.0e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 32
records_per_epoch: 50000
searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 32
entrypoint: model_def:CIFARTrial
min_validation_period:
  epochs: 1
profiling: 
  enabled: true