name: coreapi_mnist_tutorial_distributed_single
description: Train the model across slots_per_trial nodes.
entrypoint: >-
   python3 -m determined.launch.torch_distributed
   python3 model_def_distributed.py
hyperparameters:
  global_batch_size: 256
  learning_rate: 1.0
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
max_restarts: 0
records_per_epoch: 60000
searcher:
  name: single
  metric: test_loss
  smaller_is_better: true
  max_length:
    epochs: 20
resources:
  slots_per_trial: 4
