name: language modeling distributed
workspace: Solution Engineering
project: jordan
debug: false
environment:
  image: determinedai/environments-dev:python-3.10-pytorch-2.0-deepspeed-0.10.0-smartsim
  environment_variables:
    - NCCL_DEBUG=INFO
    - HF_HOME=/hf_cache
    # You may need to modify this to match your network configuration.
    #- NCCL_SOCKET_IFNAME=ens,eth,ib
resources:
  slots_per_trial: 4
  resource_pool: T4
bind_mounts:
  # Fill in shared_fs path for hf cache to speed up model loading in subsequent runs.
  - host_path: /nvmefs1/shared_nb/hf_cache
    container_path: /hf_cache
searcher:
  name: single
  max_length:
    batches: 100
  metric: eval_loss
hyperparameters:
  training_arguments:
    learning_rate: 1e-5
entrypoint: >-
  python -m determined.launch.torch_distributed
  python run_clm.py
  --model_name_or_path lmsys/vicuna-7b-v1.5
  --dataset_name wikitext
  --dataset_config_name wikitext-2-raw-v1
  --do_train
  --do_eval
  --deepspeed ds_configs/ds_config_stage_3_offload.json
  --gradient_checkpointing
  --torch_dtype float16
  --num_train_epochs 5
  --logging_strategy steps
  --logging_steps 1
  --output_dir /tmp/test-clm
  --evaluation_strategy steps
  --eval_steps 10
  --save_total_limit 3
  --seed 1337
  --save_strategy steps
  --save_steps 20
  --per_device_train_batch_size 1
  --per_device_eval_batch_size 1
  --trust_remote_code true
  --fp16
max_restarts: 0
